swagger: '2.0'
info:
  description: API for Weconnect
  version: 1.0.0
  title: Weconnect
  # My Contact Info
  contact:
    email: isaroy007@gmail.com

# tags are used for organizing operations
tags:
- name: business
  description: Business operations
- name: users
  description: Operations for user details
- name: reviews
  description: Operations for reviews

paths:
  /businesses:
    get:
      tags:
      - business
      summary: list all businesses
      operationId: Index
      description: Index endpoint for Events Manager API version 1
      produces:
      - application/json
      responses:
        200:
          description: A paged array of businesses
          examples:
            application/json:
    post:
      summary: Register a business
      tags:
       - business
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: formData
        name: name
        type: string
        description: Name of business
        required: true
      responses:
        201:
          description: Created Business Successfully
          examples:
            application/json:
              error: false
              message: New Business Added
              business:
                id: 1
                name: Andela
                details: Hire the best software engineers
                category: Ict
                location: Lagos
        400:
          description: Invalid input
          examples:
            application/json:
              error: true
              message: 'Business Name Missing'

  /businesses/{id}:
    get:
      summary: Info for a specific business
      tags:
        - business
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the business to retrieve
          type: integer
      responses:
        200:
          description: Success, business found
          examples:
            application/json:
              message: 'Success'
              error: false
              business:
                id: 3
                name: 'Bukka'
                details: 'Delicious Foods'
                location: 'Lagos'
                category: 'Resturant'
                reviews: []
        404:
          description: business not found
          examples:
            application/json:
              error: 'true'
              message: 'Business not found'