swagger: '2.0'
info:
  description: API for Weconnect
  version: 1.0.0
  title: Weconnect
  # My Contact Info
  contact:
    email: isaroy007@gmail.com

# tags are used for organizing operations
tags:
- name: business
  description: Business operations
- name: users
  description: Operations for user details
- name: reviews
  description: Operations for reviews

paths:
  /businesses:
    get:
      tags:
      - business
      summary: list all businesses
      operationId: Index
      description: Index endpoint for Events Manager API version 1
      produces:
      - application/json
      responses:
        200:
          description: A paged array of businesses
          examples:
            application/json: